run:
  tests: true
linters-settings:
  gocognit:
    min-complexity: 33
linters:
  disable-all: false
  enable-all: true
  disable:
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomnd
    - lll
    - nakedret
    - wsl
