language: go
env: GO111MODULE=on
go:
  - 1.14

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -race -count 100 -failfast ./...  # Run all the tests with the race detector enabled exclude local_test.go
  - go test -coverprofile=coverage.txt -covermode=atomic ./... # coverage
  - GCO_ENABLED=0 go build -o ./bin/deployer ./cmd/main.go #build app

after_success:
  - bash <(curl -s https://codecov.io/bash)
