projectName: project
git: "https://github.com/OtusGolang/final_project.git"
count: 2
targets:
  devel:
    type: local
    path: "testdata/releases"
    pipe:
      - name: make links
        type: links
        args:
          - from: "pathFrom"
            to: "PathTo"
          - from: "pathFrom2"
            to: "PathTo2"
      - name: run cmd
        type: command
        args:
          - command: "ls"
            args:
              - "-la"
  prod:
    type: host
    host:
      host: prod.host.ru
      auth: password
      user: user
      password: pass
    path: "/var/www/releases/"
    pipe:
      - name: make some work
        type: command
        args:
          - command: "composer"
            args:
              - "install"
      - name: make links
        type: links
        args:
          - from: "pathFrom"
            to: "PathTo"
          - from: "pathFrom2"
            to: "PathTo2"